In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%cd /content/drive/MyDrive/ConceptAI

/content/drive/MyDrive/ConceptAI

In [ ]:
!ls

bank.csv  medical_students.csv	Untitled0.ipynb

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('bank.csv')

In [ ]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [ ]:
df.shape

(45211, 17)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [ ]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [ ]:
{col:df[col].unique() for col in df}

{'age': array([58, 44, 33, 47, 35, 28, 42, 43, 41, 29, 53, 57, 51, 45, 60, 56, 32,
        25, 40, 39, 52, 46, 36, 49, 59, 37, 50, 54, 55, 48, 24, 38, 31, 30,
        27, 34, 23, 26, 61, 22, 21, 20, 66, 62, 83, 75, 67, 70, 65, 68, 64,
        69, 72, 71, 19, 76, 85, 63, 90, 82, 73, 74, 78, 80, 94, 79, 77, 86,
        95, 81, 18, 89, 84, 87, 92, 93, 88]),
 'job': array(['management', 'technician', 'entrepreneur', 'blue-collar',
        'unknown', 'retired', 'admin.', 'services', 'self-employed',
        'unemployed', 'housemaid', 'student'], dtype=object),
 'marital': array(['married', 'single', 'divorced'], dtype=object),
 'education': array(['tertiary', 'secondary', 'unknown', 'primary'], dtype=object),
 'default': array(['no', 'yes'], dtype=object),
 'balance': array([ 2143,    29,     2, ...,  8205, 14204, 16353]),
 'housing': array(['yes', 'no'], dtype=object),
 'loan': array(['no', 'yes'], dtype=object),
 'contact': array(['unknown', 'cellular', 'telephone'], dtype=object),
 'day': array([ 5,  6,  7,  8,  9, 12, 13, 14, 15, 16, 19, 20, 21, 23, 26, 27, 28,
        29, 30,  2,  3,  4, 11, 17, 18, 24, 25,  1, 10, 22, 31]),
 'month': array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'jan', 'feb',
        'mar', 'apr', 'sep'], dtype=object),
 'duration': array([ 261,  151,   76, ..., 1298, 1246, 1556]),
 'campaign': array([ 1,  2,  3,  5,  4,  6,  7,  8,  9, 10, 11, 12, 13, 19, 14, 24, 16,
        32, 18, 22, 15, 17, 25, 21, 43, 51, 63, 41, 26, 28, 55, 50, 38, 23,
        20, 29, 31, 37, 30, 46, 27, 58, 33, 35, 34, 36, 39, 44]),
 'pdays': array([ -1, 151, 166,  91,  86, 143, 147,  89, 140, 176, 101, 174, 170,
        167, 195, 165, 129, 188, 196, 172, 118, 119, 104, 171, 117, 164,
        132, 131, 123, 159, 186, 111, 115, 116, 173, 178, 110, 152,  96,
        103, 150, 175, 193, 181, 185, 154, 145, 138, 126, 180, 109, 158,
        168,  97, 182, 127, 130, 194, 125, 105, 102,  26, 179,  28, 183,
        155, 112, 120, 137, 124, 187, 190, 113, 162, 134, 169, 189,   8,
        144, 191, 184, 177,   5,  99, 133,  93,  92,  10, 100, 156, 198,
        106, 153, 146, 128,   7, 121, 160, 107,  90,  27, 197, 136, 139,
        122, 157, 149, 135,  30, 114,  98, 192, 163,  34,  95, 141,  31,
        199,  94, 108,  29, 268, 247, 253, 226, 244, 239, 245, 204, 231,
        238, 258, 230, 254, 265,  71, 223, 246, 250, 266, 240, 205, 261,
        259, 241, 260, 234, 251, 225, 161, 237, 262, 248, 255, 220, 227,
        206, 224, 249, 235, 228, 263,   2, 270, 232, 252, 207, 200, 269,
        233, 256, 273, 272, 242, 264, 208, 214, 222, 271, 203, 221, 202,
        216, 201, 257, 229, 210, 217,  75, 213,  73,  76, 267, 211, 215,
         77, 236,  82,   6, 209, 274,   1, 243, 212, 275,  80, 276,   9,
        279,  12, 280,  88, 277,  85,  84, 219,  24,  21, 282,  41, 294,
         49, 329, 307, 303, 331, 308, 300,  64, 314, 287, 330, 332, 302,
        323, 318, 333,  60, 326, 335, 313, 312, 305, 325, 327, 336, 309,
        328, 322,  39, 316, 292, 295, 310, 306, 320, 317, 289,  57, 321,
        142, 339, 301, 315, 337, 334, 340, 319,  17,  74, 148, 341, 299,
        344, 342, 324, 345, 346, 304, 281, 343, 338,  14, 347,  15, 291,
        348, 349, 285, 350, 284,  25, 283, 278,  81,   4,  87,  83,  79,
         70,  13, 293,  37,  78,  63,  22, 296, 355,  66,  19,  35, 360,
        357, 354, 351, 362, 358, 365, 298, 286, 364, 363,  47, 361, 288,
        366, 356, 352, 359, 297, 367, 353, 368,  42, 290,  67, 371, 370,
        369,  50,  36, 373, 374, 372, 311, 375, 378,  59, 379,  40,  18,
         43,  20,  69,  38, 385,  56,  55,  44, 391,  72, 390,  32,  62,
        399, 393,  65, 377, 395, 388, 389, 386,  61, 412, 405, 434, 394,
        382, 459, 440, 397, 383,  68, 461, 462, 463, 422,  51, 457, 430,
        442, 403, 454, 428, 392, 410, 401, 474, 475, 477, 478,  54, 476,
        380, 479,  45,  46, 495,  58,  48, 518,  52, 515, 520, 511, 536,
        387, 218,  33, 544, 435, 436, 555, 433, 446, 558, 469, 616, 561,
        553, 384, 592, 467, 585, 480, 421, 667, 626, 426, 595, 381, 376,
        648, 521, 452, 449, 633, 398,  53, 460, 670, 551, 414, 557, 687,
        404, 651, 686, 425, 504, 578, 674, 416, 586, 411, 756, 450, 745,
        514, 417, 424, 776, 396, 683, 529, 439, 415, 456, 407, 458, 532,
        481, 791, 701, 531, 792, 413, 445, 535, 784, 419, 455, 491, 431,
        542, 470, 472, 717, 437,   3, 782, 728, 828, 524, 562, 761, 492,
        775, 579, 493, 464, 760, 466, 465, 656, 831, 490, 432, 655, 427,
        749, 838, 769, 587, 778, 854, 779, 850, 771, 594, 842, 589, 603,
        484, 489, 486, 409, 444, 680, 808, 485, 503, 690, 772, 774, 526,
        420, 528, 500, 826, 804, 508, 547, 805, 541, 543, 871, 550, 530]),
 'previous': array([  0,   3,   1,   4,   2,  11,  16,   6,   5,  10,  12,   7,  18,
          9,  21,   8,  14,  15,  26,  37,  13,  25,  20,  27,  17,  23,
         38,  29,  24,  51, 275,  22,  19,  30,  58,  28,  32,  40,  55,
         35,  41]),
 'poutcome': array(['unknown', 'failure', 'other', 'success'], dtype=object),
 'y': array(['no', 'yes'], dtype=object)}

In [ ]:
numerical_data = df.select_dtypes(exclude='object')
categorical_data = df.select_dtypes(include='object')

In [ ]:
numerical_data.head()

   age  balance  day  duration  campaign  pdays  previous
0   58     2143    5       261         1     -1         0
1   44       29    5       151         1     -1         0
2   33        2    5        76         1     -1         0
3   47     1506    5        92         1     -1         0
4   33        1    5       198         1     -1         0

In [ ]:
categorical_data.head()

,job,marital,education,default,housing,loan,contact,month,poutcome,y
0,management,married,tertiary,no,yes,no,unknown,may,unknown,no
1,technician,single,secondary,no,yes,no,unknown,may,unknown,no
2,entrepreneur,married,secondary,no,yes,yes,unknown,may,unknown,no
3,blue-collar,married,unknown,no,yes,no,unknown,may,unknown,no
4,unknown,single,unknown,no,no,no,unknown,may,unknown,no

In [ ]:
numerical_data.to_csv('banknumericdata.csv', index=False)

In [ ]:
df1 = pd.read_csv('banknumericdata.csv')

In [ ]:
df1.head()

   age  balance  day  duration  campaign  pdays  previous
0   58     2143    5       261         1     -1         0
1   44       29    5       151         1     -1         0
2   33        2    5        76         1     -1         0
3   47     1506    5        92         1     -1         0
4   33        1    5       198         1     -1         0

In [ ]:
df1.describe().T

,count,mean,std,min,25%,50%,75%,max
age,45211.0,40.936210,10.618762,18.0,33.0,39.0,48.0,95.0
balance,45211.0,1362.272058,3044.765829,-8019.0,72.0,448.0,1428.0,102127.0
day,45211.0,15.806419,8.322476,1.0,8.0,16.0,21.0,31.0
duration,45211.0,258.163080,257.527812,0.0,103.0,180.0,319.0,4918.0
campaign,45211.0,2.763841,3.098021,1.0,1.0,2.0,3.0,63.0
pdays,45211.0,40.197828,100.128746,-1.0,-1.0,-1.0,-1.0,871.0
previous,45211.0,0.580323,2.303441,0.0,0.0,0.0,0.0,275.0

In [ ]:
ms = pd.read_csv('medical_students.csv')

In [ ]:
ms.head()

,Student ID,Age,Gender,Height,Weight,Blood Type,BMI,Temperature,Heart Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
0,1.0,18.0,Female,161.777924,72.354947,O,27.645835,NaN,95.0,109.0,203.0,No,NaN
1,2.0,NaN,Male,152.069157,47.630941,B,NaN,98.714977,93.0,104.0,163.0,No,No
2,3.0,32.0,Female,182.537664,55.741083,A,16.729017,98.260293,76.0,130.0,216.0,Yes,No
3,NaN,30.0,Male,182.112867,63.332207,B,19.096042,98.839605,99.0,112.0,141.0,No,Yes
4,5.0,23.0,Female,NaN,46.234173,O,NaN,98.480008,95.0,NaN,231.0,No,No

In [ ]:
ms.isnull().sum()/len(ms)*100

Student ID        10.0
Age               10.0
Gender            10.0
Height            10.0
Weight            10.0
Blood Type        10.0
BMI               10.0
Temperature       10.0
Heart Rate        10.0
Blood Pressure    10.0
Cholesterol       10.0
Diabetes          10.0
Smoking           10.0
dtype: float64

In [ ]:
ms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Student ID      180000 non-null  float64
 1   Age             180000 non-null  float64
 2   Gender          180000 non-null  object
 3   Height          180000 non-null  float64
 4   Weight          180000 non-null  float64
 5   Blood Type      180000 non-null  object
 6   BMI             180000 non-null  float64
 7   Temperature     180000 non-null  float64
 8   Heart Rate      180000 non-null  float64
 9   Blood Pressure  180000 non-null  float64
 10  Cholesterol     180000 non-null  float64
 11  Diabetes        180000 non-null  object
 12  Smoking         180000 non-null  object
dtypes: float64(9), object(4)
memory usage: 19.8+ MB

In [ ]:
numeric = ms.select_dtypes(exclude='object')
categoric = ms.select_dtypes(include='object')

In [ ]:
numeric.fillna(numeric.mean(),inplace=True)

In [ ]:
numeric.isnull().sum()

Student ID        0
Age               0
Height            0
Weight            0
BMI               0
Temperature       0
Heart Rate        0
Blood Pressure    0
Cholesterol       0
dtype: int64

In [ ]:
categoric.apply(lambda col:col.fillna(col.mode()[0],inplace=True))

Gender        None
Blood Type    None
Diabetes      None
Smoking       None
dtype: object

In [ ]:
categoric.isnull().sum()

Gender        0
Blood Type    0
Diabetes      0
Smoking       0
dtype: int64

In [ ]:
combine_data = pd.concat([numeric,categoric],axis=1)

In [ ]:
combine_data.head()

,Student ID,Age,Height,Weight,BMI,Temperature,Heart Rate,Blood Pressure,Cholesterol,Gender,Blood Type,Diabetes,Smoking
0,1.000000,18.000000,161.777924,72.354947,27.645835,98.600948,95.0,109.000000,203.0,Female,O,No,No
1,2.000000,26.021561,152.069157,47.630941,23.338869,98.714977,93.0,104.000000,163.0,Male,B,No,No
2,3.000000,32.000000,182.537664,55.741083,16.729017,98.260293,76.0,130.000000,216.0,Female,A,Yes,No
3,49974.042078,30.000000,182.112867,63.332207,19.096042,98.839605,99.0,112.000000,141.0,Male,B,No,Yes
4,5.000000,23.000000,174.947103,46.234173,23.338869,98.480008,95.0,114.558033,231.0,Female,O,No,No

In [ ]:
combine_data.duplicated().sum()

12572

In [ ]:
combine_data.drop_duplicates(inplace=True)

In [ ]:
categoric.columns

Index(['Gender', 'Blood Type', 'Diabetes', 'Smoking'], dtype='object')

In [ ]:
combine_data.duplicated().sum()

0

In [ ]:
encoded_data = pd.get_dummies(combine_data,columns=['Gender', 'Blood Type', 'Diabetes', 'Smoking'],drop_first=True,dtype='int')

In [ ]:
encoded_data.head()

,Student ID,Age,Height,Weight,BMI,Temperature,Heart Rate,Blood Pressure,Cholesterol,Gender_Male,Blood Type_AB,Blood Type_B,Blood Type_O,Diabetes_Yes,Smoking_Yes
0,1.000000,18.000000,161.777924,72.354947,27.645835,98.600948,95.0,109.000000,203.0,0,0,0,1,0,0
1,2.000000,26.021561,152.069157,47.630941,23.338869,98.714977,93.0,104.000000,163.0,1,0,1,0,0,0
2,3.000000,32.000000,182.537664,55.741083,16.729017,98.260293,76.0,130.000000,216.0,0,0,0,0,1,0
3,49974.042078,30.000000,182.112867,63.332207,19.096042,98.839605,99.0,112.000000,141.0,1,0,1,0,0,1
4,5.000000,23.000000,174.947103,46.234173,23.338869,98.480008,95.0,114.558033,231.0,0,0,0,1,0,0

In [ ]:
combine_data.duplicated().sum()

0